# Generated by Django 5.1.3 on 2024-11-18 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStickman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stickman_name', models.CharField(max_length=20)),
                ('stickman_clothes', models.JSONField()),
                ('stickman_img_base64', models.CharField(max_length=60000)),
                ('price', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_stickmen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
