# Generated by Django 5.1.2 on 2024-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stickmanshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedstickman',
            name='stickman_name',
            field=models.CharField(max_length=20),
        ),
    ]
