# Generated by Django 5.1.2 on 2024-11-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stickmanshop', '0002_alter_savedstickman_stickman_clothes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedstickman',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
