# Generated by Django 5.1.2 on 2024-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stickmanshop', '0003_alter_savedstickman_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedstickman',
            name='stickman_data',
            field=models.CharField(max_length=300),
        ),
    ]
