# Generated by Django 5.1.2 on 2024-11-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stickmanshop', '0003_alter_savedstickman_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedstickman',
            name='stickman_clothes',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='savedstickman',
            name='stickman_img_base64',
            field=models.CharField(max_length=60000),
        ),
        migrations.AlterField(
            model_name='savedstickman',
            name='stickman_name',
            field=models.CharField(max_length=20),
        ),
    ]
