# Generated by Django 5.1.2 on 2024-11-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stickmanshop', '0008_alter_savedstickman_stickman_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstickman',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
