# Generated by Django 5.1.2 on 2024-11-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stickmanshop', '0009_savedstickman_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedstickman',
            name='price',
            field=models.FloatField(),
        ),
    ]
