it_jokes = [
    "Why do programmers prefer dark mode? It’s light on their eyes.",
    "Why do Java developers wear glasses? Because they don’t C#!",
    "How many programmers does it take to change a light bulb? None, that's a hardware issue!",
    "Why was the computer cold? It left its Windows open.",
    "Why did the computer cross the road? To get to the other website.",
    "What’s a computer's favorite beat? An algorithm.",
    "Why did the programmer quit his job? He didn't get arrays.",
    "How do you comfort a JavaScript bug? You console it.",
    "Why do programmers prefer iOS development? Because it’s a piece of cake.",
    "Why don’t programmers like nature? It has too many bugs.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
    "What's a computer’s favorite snack? Microchips.",
    "Why did the computer go to therapy? It had too many bytes of emotional baggage.",
    "Why do programmers prefer dark mode? It’s easy on the eyes and light on the electric bill.",
    "What's a computer's least favorite food? Spam.",
    "Why did the computer keep its drink on the windowsill? Because it wanted a cold drink.",
    "How many programmers does it take to change a light bulb? None, it's a hardware problem.",
    "Why don’t programmers like to go outside? The sunlight causes too many reflections.",
    "Why do programmers hate nature? It has too many bugs.",
    "What did the server say to the networking equipment? Can I help you connect?",
    "Why did the computer go to the doctor? It had a byte problem.",
    "Why don't programmers like nature? It has too many branches.",
    "Why do programmers prefer dark mode? Light attracts bugs.",
    "What's a computer's favorite beat? An algorithm.",
    "Why did the programmer get thrown out of school? He refused to take a byte out of the principal.",
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "How do you comfort a JavaScript bug? You console it.",
    "Why do programmers prefer Linux? Because root is always in control.",
    "Why do programmers prefer dark mode? It's easier on the eyes and doesn't attract as many bugs.",
    "Why did the computer go to therapy? It had too many bytes of emotional baggage.",
    "Why was the computer cold? It left its Windows open.",
    "Why do programmers prefer dark mode? It’s light on the eyes.",
    "Why was the math book sad? Because it had too many problems.",
    "Why don't programmers like to go outside? The sunlight causes too many reflections.",
    "Why do programmers prefer iOS development? Because it’s a piece of cake.",
    "Why did the computer cross the road? To get to the other website.",
    "Why did the programmer quit his job? He didn't get arrays.",
    "What do you get when you cross a computer and a lifeguard? A screensaver.",
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "How do you comfort a JavaScript bug? You console it.",
    "Why do programmers prefer Linux? Because root is always in control.",
    "Why was the computer cold? It left its Windows open.",
    "Why do programmers prefer dark mode? It’s light on the eyes.",
    "Why did the computer cross the road? To get to the other website.",
    "What’s a computer's favorite beat? An algorithm.",
    "Why do programmers prefer iOS development? Because it’s a piece of cake.",
    "Why did the programmer quit his job? He didn't get arrays.",
    "How many programmers does it take to change a light bulb? None, that's a hardware issue!",
    "Why was the computer cold? It left its Windows open.",
    "Why did the computer cross the road? To get to the other website.",
    "What’s a computer's favorite beat? An algorithm.",
    "Why did the programmer quit his job? He didn't get arrays.",
    "How many programmers does it take to change a light bulb? None, that's a hardware issue!",
]
